# nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 기반으로 ROS까지 설치해놓은 nvgl-dev-bionic:ros 상속
FROM nvgl-dev-bionic:ros

# 이미지 빌드 중엔 CLI 환경이 사용자 입력을 받을 수 없는 환경임을 알려줌
ENV DEBIAN_FRONTEND=noninteractive

# 이미지에 패지키 설치
RUN apt-get update \
    && apt-get upgrade -y \
    && echo "===== Install Pangolin dependencies =====" \
    && apt-get install -y \
        libgl1-mesa-dev libglew-dev \
        pkg-config libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols \
        libdc1394-22-dev libraw1394-dev libuvc-dev \
        ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libavdevice-dev \
        libjpeg-dev libpng-dev libtiff5-dev libopenexr-dev libeigen3-dev \
    && echo "===== Install ORB-SLAM2 dependencies =====" \
    && apt-get install -y \
        libopencv-dev libeigen3-dev \
        libsuitesparse-dev qtdeclarative5-dev qt5-qmake libqglviewer-dev-qt5 \
    && echo "===== Install Ceres dependencies =====" \
    && apt-get install -y \
        libeigen3-dev libgoogle-glog-dev libgflags-dev libsuitesparse-dev libatlas-base-dev

